### ISSUE TITLE
TypeError: run() got an unexpected keyword argument 'capture_output'

### ISSUE THREAD

**Issue by bda65hp** [unode/firefox_decrypt#93]
Hi,

I'm running Arch Linux (updated this today) with pass 1.7.4 and Firefox 112.
It crash when using --format pass:

  python3.11 firefox_decrypt.py --format pass
  Select the Mozilla profile you wish to decrypt
  1 -> xxxxxx.default
  2 -> yyyyyy.default-release
  2
  Traceback (most recent call last):
    File "/home/bruno/src/firefox_decrypt/firefox_decrypt.py", line 1125, in <module>
      run()
    File "/home/bruno/src/firefox_decrypt/firefox_decrypt.py", line 1116, in run
      main()
    File "/home/bruno/src/firefox_decrypt/firefox_decrypt.py", line 1108, in main
      formatter.output()
    File "/home/bruno/src/firefox_decrypt/firefox_decrypt.py", line 653, in output
      self.test_pass_cmd()
    File "/home/bruno/src/firefox_decrypt/firefox_decrypt.py", line 664, in test_pass_cmd
      p = run([self.cmd, "ls"], capture_output=True, text=True)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  TypeError: run() got an unexpected keyword argument 'capture_output'

pass work well here since some years.

**Comment by unode** [comment]
What Python version are you using?

**Comment by unode** [comment]
Apologies, this was a bug introduced in 1a2bb7b8d7896ec7443d9bc599af08fbfc9a326f.
Now fixed in the main branch.

**Comment by bda65hp** [comment]
Oh thanks :) :+1:
